repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Sprawdź najnowszą wersję, v5.0.0 jest stabilna w 2026
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.5
    hooks:
      # Run the linter.
      - id: ruff-check
#      - id: ruff
        files: '^.*\/.*\.py$'
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
#        files: '(^.*/.*\.ipynb$)|(^.*/.*\.py$)'
        args: [ --check ]
